version: '2'
services:
  node1:
    image: cajan2/naivechain_v1
    ports:
    - "3001:3001"
  node2:
    image: cajan2/naivechain_v1
    environment:
      - PEERS=ws://node1:6001
    ports:
    - "3002:3001"
    links:
      - node1:node1
  node3:
    image: cajan2/naivechain_v1
    environment:
      - PEERS=ws://node2:6001
    ports:
    - "3003:3001"
    links:
      - node2:node2
